"use client";

export default function Page() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center py-2">
      <h1 className="text-6xl font-bold">
        <span className="text-blue-600">Focus</span> Timer
      </h1>
      <p className="mt-3 text-2xl">
        Generated by Ali Cagatay using{" "}
        <a className="text-blue-600" href="https://create.t3.gg/">
          {" "}
          the T3 Stack
        </a>
      </p>
    </div>
  );
}
